
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getQuests(props: GetQuestsRequest) : Promise<Result<Quest[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_quests", { props }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSubQuests(questId: string) : Promise<Result<Quest[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_sub_quests", { questId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getQuest(id: string) : Promise<Result<Quest, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_quest", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addQuest(props: AddQuestRequest) : Promise<Result<Quest, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_quest", { props }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateQuest(props: UpdateQuestRequest) : Promise<Result<Quest, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_quest", { props }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteQuest(props: DeleteQuestRequest) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_quest", { props }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateQuestsOrder(props: UpdateQuestsOrderRequest) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_quests_order", { props }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async moveQuest(props: MoveQuestRequest) : Promise<Result<Quest, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("move_quest", { props }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async uploadDescriptionAsset(props: UploadDescriptionAssetRequest) : Promise<Result<QuestDescriptionAsset, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("upload_description_asset", { props }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async uploadDescriptionImage(props: UploadDescriptionAssetRequest) : Promise<Result<QuestDescriptionAsset, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("upload_description_image", { props }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async discardDescriptionDraft(props: DiscardDescriptionDraftRequest) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("discard_description_draft", { props }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AddQuestRequest = { title: string; parent_id: string | null; description?: string | null; description_draft_id?: string | null }
export type DeleteQuestRequest = { id: string }
export type DiscardDescriptionDraftRequest = { draft_id: string }
export type GetQuestsRequest = { date: string | null; filter: string }
export type MoveQuestRequest = { id: string; parent_id: string | null; index: number }
export type Quest = { id: string; title: string; description: string | null; completed: boolean; createdAt: string; completedAt: string | null; orderIndex: number; parentId: string | null; hasChildren: boolean | null; descriptionAssets: QuestDescriptionAsset[] | null; children: Quest[] | null }
export type QuestDescriptionAsset = { id: string; questId: string | null; draftId: string | null; relativePath: string; originalFilename: string | null; mimeType: string; byteSize: number; createdAt: string }
export type UpdateQuestData = { title?: string | null; description?: string | null; completed?: boolean | null }
export type UpdateQuestRequest = { id: string; data: UpdateQuestData }
export type UpdateQuestsOrderRequest = { ids: string[] }
export type UploadDescriptionAssetRequest = { quest_id: string | null; draft_id: string | null; filename: string | null; mime_type: string; bytes: number[] }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
