/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as QuestsQuestIdImport } from './routes/quests.$questId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const QuestsQuestIdRoute = QuestsQuestIdImport.update({
  id: '/quests/$questId',
  path: '/quests/$questId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/quests/$questId': {
      id: '/quests/$questId'
      path: '/quests/$questId'
      fullPath: '/quests/$questId'
      preLoaderRoute: typeof QuestsQuestIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/quests/$questId': typeof QuestsQuestIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/quests/$questId': typeof QuestsQuestIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/quests/$questId': typeof QuestsQuestIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/quests/$questId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/quests/$questId'
  id: '__root__' | '/' | '/quests/$questId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QuestsQuestIdRoute: typeof QuestsQuestIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QuestsQuestIdRoute: QuestsQuestIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/quests/$questId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/quests/$questId": {
      "filePath": "quests.$questId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
